--- 
ReportDefinitions: 
  - 
    moduleName: rainmaker-pension
    query: "select application_number,name as applicantName, date_of_retirement from eg_pension_workflow_header pwr join public.eg_pension_employee pe on pwr.pension_employee_id=pe.uuid where 1=1 AND pwr.workflow_type='RRP_SERVICE'"
    reportName: RegularNormalPension
    searchParams: 
      - 
        isMandatory: true
        label: reports.rainmaker-pgr.datefrom
        name: fromDate
        searchClause: "AND pwr.application_date >= $fromDate"
        source: eg_pension_workflow_header
        type: epoch
      - 
        isMandatory: true
        label: reports.rainmaker-pgr.dateto
        name: toDate
        searchClause: "AND pwr.application_date <= $toDate"
        source: eg_pension_workflow_header
        type: epoch
    sourceColumns: 
      - 
        label: PENSION_APPLICATION_NUMBER
        name: application_number
        source: eg_pension_workflow_header
        type: string
      - 
        label: "Applicant Name"
        name: applicantName
        source: eg_pension_workflow_header
        type: string
      - 
        label: PENSION_DOR
        name: date_of_retirement
        source: eg_pension_workflow_header
        type: epoch
  - 
    moduleName: rainmaker-pension
    query: "select  fma, miscellaneous, over_payment, income_tax, cess, basic_pension, additional_pension, commuted_pension, net_deductions, final_calculated_pension, interim_relief, da, total_pension, pension_deductions, wound_extraordinary_pension, attendant_allowance from eg_pension_revision pr join eg_pension_pensioner pp on pr.pensioner_id=pp.uuid where 1=1 AND pp.active=true AND pr.active=true"
    reportName: MonthlyPensionDrawn
    searchParams: 
      - 
        isMandatory: true
        label: Year
        name: Year
        pattern: "list://2020:2020,2021:2021,2022:2022,2023:2023,2024:2024,2025:2025"
        searchClause: "AND pr.effective_start_year>= $Year AND pr.effective_start_month>=$Month and pr.effective_end_year<=$Year and pr.effective_end_month<=$Month"
        source: eg_pension_revision
        type: singlevaluelist
        wrapper: true
      - 
        isMandatory: true
        label: Month
        name: Month
        pattern: "list://1:1,2:2,3:3,4:4,5:5,6:6,7:7,8:8,9:9,10:10,11:11,12:12"
        searchClause: "OR pr.effective_start_year>=$Year and pr.effective_start_month>=$Month"
        source: eg_pension_revision
        type: singlevaluelist
        wrapper: true
    sourceColumns: 
      - 
        label: PENSION_EMPLOYEE_PENSION_FMA
        name: fma
        source: eg_pension_revision
        total: true
        type: string
      - 
        label: PENSION_EMPLOYEE_PENSION_MISCELLANEOUS
        name: miscellaneous
        source: eg_pension_revision
        total: true
        type: string
      - 
        label: PENSION_EMPLOYEE_PENSION_OVERPAYMENT
        name: over_payment
        source: eg_pension_revision
        total: true
        type: string
      - 
        label: PENSION_EMPLOYEE_PENSION_INCOME_TAX
        name: income_tax
        source: eg_pension_revision
        total: true
        type: string
      - 
        label: PENSION_EMPLOYEE_PENSION_CESS
        name: cess
        source: eg_pension_revision
        total: true
        type: string
      - 
        label: PENSION_EMPLOYEE_PENSION_BP_R
        name: basic_pension
        source: eg_pension_revision
        total: true
        type: string
      - 
        label: PENSION_EMPLOYEE_PENSION_AP_R
        name: additional_pension
        source: eg_pension_revision
        total: true
        type: string
      - 
        label: PENSION_EMPLOYEE_PENSION_COMMMUTED_PEENSION_R
        name: commuted_pension
        source: eg_pension_revision
        total: true
        type: string
      - 
        label: PENSION_EMPLOYEE_PENSION_NET_DEDUCTION_R
        name: net_deductions
        source: eg_pension_revision
        total: true
        type: string
      - 
        label: PENSION_EMPLOYEE_PENSION_FINAL_DEDUCTION_R
        name: final_calculated_pension
        source: eg_pension_revision
        total: true
        type: string
      - 
        label: PENSION_EMPLOYEE_PENSION_IR_R
        name: interim_relief
        source: eg_pension_revision
        total: true
        type: string
      - 
        label: PENSION_EMPLOYEE_PENSION_DA_R
        name: da
        source: eg_pension_revision
        total: true
        type: string
      - 
        label: PENSION_EMPLOYEE_PENSION_TP_R
        name: total_pension
        source: eg_pension_revision
        total: true
        type: string
      - 
        label: "Pension Deductions"
        name: pension_deductions
        source: eg_pension_revision
        total: true
        type: string
      - 
        label: "Wound Extraordinary Pension"
        name: wound_extraordinary_pension
        source: eg_pension_revision
        total: true
        type: string
      - 
        label: "Attendant Allowance"
        name: attendant_allowance
        source: eg_pension_revision
        total: true
        type: string
  - 
    moduleName: rainmaker-pension
    query: "select application_number,name as applicantName, date_of_retirement from eg_pension_workflow_header pwr join public.eg_pension_employee pe on pwr.pension_employee_id=pe.uuid where 1=1 AND pwr.workflow_type='DOE_SERVICE'"
    reportName: DeathOfAnEmployee
    searchParams: 
      - 
        isMandatory: true
        label: reports.rainmaker-pgr.datefrom
        name: fromDate
        searchClause: "AND pwr.application_date >= $fromDate"
        source: eg_pension_workflow_header
        type: epoch
      - 
        isMandatory: true
        label: reports.rainmaker-pgr.dateto
        name: toDate
        searchClause: "AND pwr.application_date <= $toDate"
        source: eg_pension_workflow_header
        type: epoch
    sourceColumns: 
      - 
        label: PENSION_APPLICATION_NUMBER
        name: application_number
        source: eg_pension_workflow_header
        type: string
      - 
        label: "Applicant Name"
        name: applicantName
        source: eg_pension_workflow_header
        type: string
      - 
        label: PENSION_DOR
        name: date_of_retirement
        source: eg_pension_workflow_header
        type: epoch
  - 
    moduleName: rainmaker-pension
    query: "select application_number,name as applicantName, date_of_retirement from eg_pension_workflow_header pwr join public.eg_pension_employee pe on pwr.pension_employee_id=pe.uuid where 1=1 AND pwr.workflow_type='DOP_SERVICE'"
    reportName: DeathOfPensioner
    searchParams: 
      - 
        isMandatory: true
        label: reports.rainmaker-pgr.datefrom
        name: fromDate
        searchClause: "AND pwr.application_date >= $fromDate"
        source: eg_pension_workflow_header
        type: epoch
      - 
        isMandatory: true
        label: reports.rainmaker-pgr.dateto
        name: toDate
        searchClause: "AND pwr.application_date <= $toDate"
        source: eg_pension_workflow_header
        type: epoch
    sourceColumns: 
      - 
        label: PENSION_APPLICATION_NUMBER
        name: application_number
        source: eg_pension_workflow_header
        type: string
      - 
        label: "Applicant Name"
        name: applicantName
        source: eg_pension_workflow_header
        type: string
      - 
        label: PENSION_DOR
        name: date_of_retirement
        source: eg_pension_workflow_header
        type: epoch
  - 
    moduleName: rainmaker-pension
    query: "select employee_hrms_id as id, employee_hrms_code as code,name,gender, employee_type, date_of_birth,date_of_retirement from eg_pension_employee WHERE 1=1"
    reportName: EmployeeToBeRetired
    searchParams: 
      - 
        isMandatory: true
        label: reports.rainmaker-pgr.datefrom
        name: fromDate
        searchClause: "AND eg_pension_employee.date_of_retirement >= $fromDate"
        source: eg_pension_employee
        type: epoch
      - 
        isMandatory: true
        label: reports.rainmaker-pgr.dateto
        name: toDate
        searchClause: "AND eg_pension_employee.date_of_retirement <= $toDate"
        source: eg_pension_employee
        type: epoch
    sourceColumns: 
      - 
        label: PENSION_EMPLOYEE_CODE
        name: code
        source: eg_pension_employee
        type: string
      - 
        label: PENSION_EMPLOYEE_NAME
        name: name
        source: eg_pension_employee
        type: string
      - 
        label: PENSION_EMPLOYEE_GENDER
        name: gender
        source: eg_pension_employee
        type: string
      - 
        label: PENSION_EMPLOYEE_TYPE
        name: "employee_type"
        source: eg_pension_employee
        total: false
        type: string
      - 
        label: PENSION_DOB
        name: date_of_birth
        source: eg_pension_employee
        total: false
        type: epoch
      - 
        label: PENSION_DOR
        name: date_of_retirement
        source: eg_pension_employee
        total: false
        type: epoch

