serviceMaps:
 serviceName: ws-service
 mappings:
 - version: 1.0
   name: BillGeneration
   description: Insert Bill data from excel
   fromTopic: save-ws-waterbilldetails
   isTransaction: true
   queryMaps:
    - query: INSERT INTO public.eg_ws_savebilling(id, cccode, divsdiv, consumercode, billcycle, billgroup, subgroup, billtype, name, address, add1, add2, add3, add4, add5, cesscharge, netamount, grossamount, surcharge, totalnetamount, totalsurcharge, totalgrossamount, fixchargecode, fixcharge, duedatecash, duedatecheque, status, billid, paymentid, paymentstatus, createdby, createdtime,isFileGenerated ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?) ON CONFLICT (consumercode) DO UPDATE SET cccode=?, divsdiv=?, consumercode=?, billcycle=?, billgroup=?, subgroup=?, billtype=?, "name"=?, address=?, add1=?, add2=?, add3=?, add4=?, add5=?, cesscharge=?, netamount=?, grossamount=?, surcharge=?, totalnetamount=?, totalsurcharge=?, totalgrossamount=?, fixchargecode=?, fixcharge=?, duedatecash=?, duedatecheque=?, status=?, billid=?, paymentid=?, paymentstatus=?, totalAmount_paid=?, paymentMode=?,isFileGenerated=?, lastmodifiedby=?, lastmodifiedtime=?;

      basePath: $.billGeneration.*
      jsonMaps:

       - jsonPath: $.billGeneration.*.billGenerationId

       - jsonPath: $.billGeneration.*.ccCode

       - jsonPath: $.billGeneration.*.divSdiv

       - jsonPath: $.billGeneration.*.consumerCode

       - jsonPath: $.billGeneration.*.billCycle

       - jsonPath: $.billGeneration.*.billGroup

       - jsonPath: $.billGeneration.*.subGroup

       - jsonPath: $.billGeneration.*.billType

       - jsonPath: $.billGeneration.*.name

       - jsonPath: $.billGeneration.*.address

       - jsonPath: $.billGeneration.*.add1

       - jsonPath: $.billGeneration.*.add2

       - jsonPath: $.billGeneration.*.add3

       - jsonPath: $.billGeneration.*.add4

       - jsonPath: $.billGeneration.*.add5

       - jsonPath: $.billGeneration.*.cessCharge

       - jsonPath: $.billGeneration.*.netAmount

       - jsonPath: $.billGeneration.*.grossAmount

       - jsonPath: $.billGeneration.*.surcharge

       - jsonPath: $.billGeneration.*.totalNetAmount

       - jsonPath: $.billGeneration.*.totalSurcharge

       - jsonPath: $.billGeneration.*.totalGrossAmount

       - jsonPath: $.billGeneration.*.fixChargeCode

       - jsonPath: $.billGeneration.*.fixCharge

       - jsonPath: $.billGeneration.*.dueDateCash

       - jsonPath: $.billGeneration.*.dueDateCheque

       - jsonPath: $.billGeneration.*.status

       - jsonPath: $.billGeneration.*.billId
       
       - jsonPath: $.billGeneration.*.paymentId 

       - jsonPath: $.billGeneration.*.paymentStatus
       
       - jsonPath: $.billGeneration.*.auditDetails.createdBy 

       - jsonPath: $.billGeneration.*.auditDetails.createdTime 

       - jsonPath: $.billGeneration.*.isFileGenerated

       - jsonPath: $.billGeneration.*.ccCode

       - jsonPath: $.billGeneration.*.divSdiv

       - jsonPath: $.billGeneration.*.consumerCode

       - jsonPath: $.billGeneration.*.billCycle

       - jsonPath: $.billGeneration.*.billGroup

       - jsonPath: $.billGeneration.*.subGroup

       - jsonPath: $.billGeneration.*.billType

       - jsonPath: $.billGeneration.*.name

       - jsonPath: $.billGeneration.*.address

       - jsonPath: $.billGeneration.*.add1

       - jsonPath: $.billGeneration.*.add2

       - jsonPath: $.billGeneration.*.add3

       - jsonPath: $.billGeneration.*.add4

       - jsonPath: $.billGeneration.*.add5

       - jsonPath: $.billGeneration.*.cessCharge

       - jsonPath: $.billGeneration.*.netAmount

       - jsonPath: $.billGeneration.*.grossAmount

       - jsonPath: $.billGeneration.*.surcharge

       - jsonPath: $.billGeneration.*.totalNetAmount

       - jsonPath: $.billGeneration.*.totalSurcharge

       - jsonPath: $.billGeneration.*.totalGrossAmount

       - jsonPath: $.billGeneration.*.fixChargeCode

       - jsonPath: $.billGeneration.*.fixCharge

       - jsonPath: $.billGeneration.*.dueDateCash

       - jsonPath: $.billGeneration.*.dueDateCheque

       - jsonPath: $.billGeneration.*.status

       - jsonPath: $.billGeneration.*.billId
       
       - jsonPath: $.billGeneration.*.paymentId 

       - jsonPath: $.billGeneration.*.paymentStatus 

       - jsonPath: $.billGeneration.*.totalAmountPaid 

       - jsonPath: $.billGeneration.*.paymentMode 

       - jsonPath: $.billGeneration.*.isFileGenerated
       
       - jsonPath: $.billGeneration.*.auditDetails.createdBy 

       - jsonPath: $.billGeneration.*.auditDetails.createdTime



 - version: 1.0
   name: WS billing file generation history
   description: Save File generation history of billing
   fromTopic: save-ws-billing-filestoreids
   isTransaction: true
   queryMaps:

    - query: INSERT INTO public.eg_ws_billfile_history(id, filestore_url, filestore_id, filegeneration_time) VALUES (?, ?, ?, ?);

      basePath: $.billGenerationFile
      jsonMaps:

       - jsonPath: $.billGenerationFile.billGenerationFileId

       - jsonPath: $.billGenerationFile.billFileStoreUrl

       - jsonPath: $.billGenerationFile.billFileStoreId

       - jsonPath: $.billGenerationFile.fileGenerationTime

 - version: 1.0
   description: update water billing status
   fromTopic: update-ws-bill-payment
   isTransaction: true
   queryMaps:

        - query: UPDATE public.eg_ws_savebilling set status=?, billid=?, paymentid=?,paymentMode=?, paymentstatus=?,totalAmount_paid=? where consumercode = ? ;
          basePath: $.billGeneration
          jsonMaps:

           - jsonPath: $.billGeneration.status
    
           - jsonPath: $.billGeneration.billId
    
           - jsonPath: $.billGeneration.paymentId
    
           - jsonPath: $.billGeneration.paymentMode
    
           - jsonPath: $.billGeneration.paymentStatus
    
           - jsonPath: $.billGeneration.totalAmountPaid
    
           - jsonPath: $.billGeneration.consumerCode

 - version: 1.0
   description: Update billing file Status
   fromTopic: update-ws-bill-file-flag
   isTransaction: true
   queryMaps:

        - query: UPDATE public.eg_ws_savebilling set isFileGenerated=true where consumercode = ? ;
          basePath: $.billGeneration.*
          jsonMaps:

            - jsonPath: $.billGeneration.*.consumerCode