ServiceMaps:
 serviceName: echallan
 version: 1.0.0
 mappings:
  - topic: ec-services-save-item
    configKey: INDEX
    indexes:
    - name: ec-services-item-master-index-v1
      type: item-master
      id: $.itemUuid, $.tenantId
      isBulk: false
      timeStampField: $.createdTime
      jsonPath: $.RequestBody

  - topic: ec-services-update-item
    configKey: INDEX
    indexes:
    - name: ec-services-item-master-index-v1
      type: item-master
      id: $.itemUuid, $.tenantId
      isBulk: false
      timeStampField: $.createdTime
      jsonPath: $.RequestBody
   
  - topic: ec-services-save-fine
    configKey: INDEX
    indexes:
    - name: ec-services-fine-master-index-v1
      type: fine-master
      id: $.fineUuid, $.tenantId
      isBulk: false
      timeStampField: $.createdTime
      jsonPath: $.RequestBody

  - topic: ec-services-update-fine
    configKey: INDEX
    indexes:
    - name: ec-services-fine-master-index-v1
      type: fine-master
      id: $.fineUuid, $.tenantId
      isBulk: false
      timeStampField: $.createdTime
      jsonPath: $.RequestBody      

  - topic: ec-services-create-store-item
    configKey: INDEX
    indexes:
    - name: ec-services-store-index-v1
      type: store-item
      id: $.storeItemUuid, $.challanUuid , $.tenantId
      isBulk: true
      timeStampField: $.createdTime
      jsonPath: $.RequestBody.storeItemRegister

  - topic: ec-services-update-store-item
    configKey: INDEX
    indexes:
    - name: ec-services-store-index-v1
      type: store-item
      id: $.challanUuid
      isBulk: false
      timeStampField: $.createdTime
      jsonPath: $.RequestBody

  - topic: ec-services-generate-challan
    configKey: INDEX
    indexes:
    - name: ec-services-challan-index-v1
      type:  challan
      id: $.violationUuid , $.challanUuid, $.tenantId
      isBulk: false
      timeStampField: $.createdTime
      jsonPath: $.RequestBody

  - topic: ec-services-update-challan
    configKey: INDEX
    indexes:
    - name: ec-services-challan-index-v1
      type:  challan
      id:  $.challanUuid
      isBulk: false
      timeStampField: $.lastModifiedTime
      jsonPath: $.RequestBody

  - topic: ec-services-create-vendor
    configKey: INDEX
    indexes:
    - name: ec-services-vendor-index-v1
      type: vendor-master
      id: $.vendorUuid, $.tenantId
      isBulk: true
      timeStampField: $.createdTime
      jsonPath: $.RequestBody.vendorRegistrationList

  - topic: ec-services-update-store-offline-payment
    configKey: INDEX
    indexes:
    - name: ec-services-store-index-v1
      type: store-item
      id: $.challanUuid
      isBulk: false
      timeStampField: $.lastModifiedTime
      jsonPath: $.RequestBody

  - topic: ec-services-update-auction
    configKey: INDEX
    indexes:
    - name: ec-services-auction-index-v1
      type: auction-master
      id: $.auctionUuid , $.challanUuid, $.tenantId
      isBulk: false
      timeStampField: $.lastModifiedTime
      jsonPath: $.RequestBody      
 
  - topic: ec-services-update-auction-rejection
    configKey: INDEX
    indexes:
    - name: ec-services-auction-index-v1
      type: auction-master
      id: $.auctionUuid , $.challanUuid, $.tenantId
      isBulk: false
      timeStampField: $.lastModifiedTime
      jsonPath: $.RequestBody

  - topic: ec-services-update-vendor
    configKey: INDEX
    indexes:
    - name: ec-services-vendor-index-v1
      type: vendor-master
      id: $.vendorUuid, $.tenantId
      isBulk: true
      timeStampField: $.createdTime
      jsonPath: $.RequestBody.vendorRegistrationList
      
  - topic: ec-services-save-auction
    configKey: INDEX
    indexes:
    - name: ec-services-auction-index-v1
      type: auction-master
      id: $.auctionUuid, $.violationUuid, $.challanUuid, $.tenantId
      isBulk: false
      timeStampField: $.createdTime
      jsonPath: $.RequestBody

  - topic: ec-services-save-payment-history
    configKey: INDEX
    indexes:
    - name: ec-services-payment-index-v1
      type: payment
      id: $.paymentUuid , $.tenantId
      isBulk: false
      timeStampField: $.createdTime
      jsonPath: $.RequestBody  

  - topic: ec-services-create-device-source
    configKey: INDEX
    indexes:
    - name: ec-services-device-detail-index-v1
      type: device-source
      id: $.sourceUuid, $.tenantId
      isBulk: false
      timeStampField: $.createdTime
      jsonPath: $.RequestBody      